### ISSUE TITLE
As training progresses, the object becomes larger, similar to a "zoom in" effect.

### ISSUE THREAD

**Issue by ByChelsea** [cxh0519/threestudio-gaussiandreamer#1]
Hi, thanks for your great work!

Have you ever encountered a situation during training where the object becomes increasingly larger? I only use the Stable Diffusion 2-1 base SDS loss for supervision, with the prompt being "a pineapple".
![efcd8fbf746cff2029d9cde122bcdb3](https://github.com/cxh0519/threestudio-gaussiandreamer/assets/67221921/a4fc524c-a6dd-4b81-9e01-5558cafca6c0)

**Comment by cxh0519** [comment]
I haven't encountered such an issue in my tests.
It seems like you didn't provide a geometry prior (e.g. shap-e) which is important for GaussianDreamer, or you can use MVDream as the 2D diffusion guidance.
It would be better if you provided more details, such as the specific command.

**Comment by ByChelsea** [comment]
To be honest, I don't quite understand what you mean by "not providing geometric priors". I initialized 3DGS randomly as a sphere and am attempting to use a text-to-image model for supervision.

**Comment by cxh0519** [comment]
"Providing geometric priors" means using Shap-E or Openlrm to initialize the 3dgs instead of using a sphere. As a re-implementation of GaussianDreamer, this codebase requires a meaningful initialization to achieve reasonable results.

For using 2D diffusion merely, you can refer to this codebase [https://github.com/DSaurus/threestudio-3dgs](https://github.com/DSaurus/threestudio-3dgs). However, even in their codebase, sphere initialization leads to more training time and low-quality results from my experience.

**Comment by ByChelsea** [comment]
Got it, thanks!
